### ISSUE TITLE
Add instructions on how to use the bot in the tip tweets

### ISSUE THREAD

**Issue by fernandofeitosa** [mitche50/NanoTipBot#23]
I've seen that a lot of times people get tipped but have no idea what to do, as the message `You have successfully sent your Nano - HASH` doesn't give any information to people that have never used nano before.

My idea would be to either
1. Send another tweet with instructions on how to use the bot
or, even better
2. Attach an image with instructions to the tweet so people know what to do when getting a tip. (I've sketched something really fast so you understand what I am saying 👇 . This wasn't supposed to be a final version at all, so I can change the copywriting/steps in case you would like to use my image.)
![nano_tip_bot](https://user-images.githubusercontent.com/3979786/121598902-9c11da00-ca42-11eb-9275-b68ff42f94e6.png)

**Comment by mitche50** [comment]
This project is not under active development.  If you'd like to contribute, please submit a PR with documentation on what you completed and I can review and potentially merge.
